//
// Copyright 2021-2023 OpsMx, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Annotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Annotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Annotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EndpointHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Configured    bool                   `protobuf:"varint,3,opt,name=configured,proto3" json:"configured,omitempty"`
	Namespaces    []string               `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"` // used for kubernetes mostly
	Annotations   []*Annotation          `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointHealth) Reset() {
	*x = EndpointHealth{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointHealth) ProtoMessage() {}

func (x *EndpointHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointHealth.ProtoReflect.Descriptor instead.
func (*EndpointHealth) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointHealth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EndpointHealth) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *EndpointHealth) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *EndpointHealth) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointHealth      `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,5,opt,name=agentInfo,proto3" json:"agentInfo,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetEndpoints() []*EndpointHealth {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *HelloRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *HelloRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   []*Annotation          `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Endpoints     []*EndpointHealth      `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Annotations   []*Annotation          `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *HelloResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HelloResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HelloResponse) GetEndpoints() []*EndpointHealth {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *HelloResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloResponse) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Headers       []*HttpHeader          `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	ContentLength int64                  `protobuf:"varint,5,opt,name=contentLength,proto3" json:"contentLength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHeaders) Reset() {
	*x = TunnelHeaders{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHeaders) ProtoMessage() {}

func (x *TunnelHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHeaders.ProtoReflect.Descriptor instead.
func (*TunnelHeaders) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelHeaders) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *TunnelHeaders) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TunnelHeaders) GetHeaders() []*HttpHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TunnelHeaders) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type HttpHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeader.ProtoReflect.Descriptor instead.
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *HttpHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HttpHeader) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type WaitForRequestArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForRequestArgs) Reset() {
	*x = WaitForRequestArgs{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForRequestArgs) ProtoMessage() {}

func (x *WaitForRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForRequestArgs.ProtoReflect.Descriptor instead.
func (*WaitForRequestArgs) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{8}
}

// TunnelRequest causes the receiving side to begin an HTTP tunnel.
type TunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	URI           string                 `protobuf:"bytes,6,opt,name=URI,proto3" json:"URI,omitempty"`
	Headers       []*HttpHeader          `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	IsKeepalive   bool                   `protobuf:"varint,9,opt,name=isKeepalive,proto3" json:"isKeepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRequest) Reset() {
	*x = TunnelRequest{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest) ProtoMessage() {}

func (x *TunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest.ProtoReflect.Descriptor instead.
func (*TunnelRequest) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *TunnelRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *TunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TunnelRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TunnelRequest) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

func (x *TunnelRequest) GetHeaders() []*HttpHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TunnelRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TunnelRequest) GetIsKeepalive() bool {
	if x != nil {
		return x.IsKeepalive
	}
	return false
}

type StartTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *StartTunnelResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{11}
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{12}
}

type StreamFlow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamFlow_StreamId
	//	*StreamFlow_Headers
	//	*StreamFlow_Data
	//	*StreamFlow_Cancel
	//	*StreamFlow_Done
	//	*StreamFlow_Keepalive
	Event         isStreamFlow_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlow) Reset() {
	*x = StreamFlow{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlow) ProtoMessage() {}

func (x *StreamFlow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlow.ProtoReflect.Descriptor instead.
func (*StreamFlow) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *StreamFlow) GetEvent() isStreamFlow_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamFlow) GetStreamId() string {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_StreamId); ok {
			return x.StreamId
		}
	}
	return ""
}

func (x *StreamFlow) GetHeaders() *TunnelHeaders {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_Headers); ok {
			return x.Headers
		}
	}
	return nil
}

func (x *StreamFlow) GetData() *Data {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *StreamFlow) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *StreamFlow) GetDone() *Done {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *StreamFlow) GetKeepalive() string {
	if x != nil {
		if x, ok := x.Event.(*StreamFlow_Keepalive); ok {
			return x.Keepalive
		}
	}
	return ""
}

type isStreamFlow_Event interface {
	isStreamFlow_Event()
}

type StreamFlow_StreamId struct {
	StreamId string `protobuf:"bytes,1,opt,name=streamId,proto3,oneof"`
}

type StreamFlow_Headers struct {
	Headers *TunnelHeaders `protobuf:"bytes,2,opt,name=headers,proto3,oneof"`
}

type StreamFlow_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type StreamFlow_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type StreamFlow_Done struct {
	Done *Done `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

type StreamFlow_Keepalive struct {
	Keepalive string `protobuf:"bytes,6,opt,name=keepalive,proto3,oneof"`
}

func (*StreamFlow_StreamId) isStreamFlow_Event() {}

func (*StreamFlow_Headers) isStreamFlow_Event() {}

func (*StreamFlow_Data) isStreamFlow_Event() {}

func (*StreamFlow_Cancel) isStreamFlow_Event() {}

func (*StreamFlow_Done) isStreamFlow_Event() {}

func (*StreamFlow_Keepalive) isStreamFlow_Event() {}

type StreamFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlowResponse) Reset() {
	*x = StreamFlowResponse{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlowResponse) ProtoMessage() {}

func (x *StreamFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlowResponse.ProtoReflect.Descriptor instead.
func (*StreamFlowResponse) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{14}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *PingRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	EchoedTs      uint64                 `protobuf:"varint,4,opt,name=echoedTs,proto3" json:"echoedTs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tunnel_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_tunnel_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *PingResponse) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PingResponse) GetEchoedTs() uint64 {
	if x != nil {
		return x.EchoedTs
	}
	return 0
}

var File_internal_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_internal_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/tunnel/tunnel.proto\x12\x06tunnel\"6\n" +
	"\n" +
	"Annotation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xae\x01\n" +
	"\x0eEndpointHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"configured\x18\x03 \x01(\bR\n" +
	"configured\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x124\n" +
	"\vannotations\x18\a \x03(\v2\x12.tunnel.AnnotationR\vannotations\"\xab\x01\n" +
	"\fHelloRequest\x124\n" +
	"\tendpoints\x18\x03 \x03(\v2\x16.tunnel.EndpointHealthR\tendpoints\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12/\n" +
	"\tagentInfo\x18\x05 \x01(\v2\x11.tunnel.AgentInfoR\tagentInfo\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"A\n" +
	"\tAgentInfo\x124\n" +
	"\vannotations\x18\x01 \x03(\v2\x12.tunnel.AnnotationR\vannotations\"\xcf\x01\n" +
	"\rHelloResponse\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\tR\aagentId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\tendpoints\x18\x03 \x03(\v2\x16.tunnel.EndpointHealthR\tendpoints\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x124\n" +
	"\vannotations\x18\x05 \x03(\v2\x12.tunnel.AnnotationR\vannotations\"6\n" +
	"\x04Data\x12\x1a\n" +
	"\bstreamId\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x9f\x01\n" +
	"\rTunnelHeaders\x12\x1a\n" +
	"\bstreamId\x18\x01 \x01(\tR\bstreamId\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x03 \x01(\x05R\n" +
	"statusCode\x12,\n" +
	"\aheaders\x18\x04 \x03(\v2\x12.tunnel.HttpHeaderR\aheaders\x12$\n" +
	"\rcontentLength\x18\x05 \x01(\x03R\rcontentLength\"8\n" +
	"\n" +
	"HttpHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x14\n" +
	"\x12WaitForRequestArgs\"\xe1\x01\n" +
	"\rTunnelRequest\x12\x1a\n" +
	"\bstreamId\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x10\n" +
	"\x03URI\x18\x06 \x01(\tR\x03URI\x12,\n" +
	"\aheaders\x18\a \x03(\v2\x12.tunnel.HttpHeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\b \x01(\fR\x04body\x12 \n" +
	"\visKeepalive\x18\t \x01(\bR\visKeepalive\"1\n" +
	"\x13StartTunnelResponse\x12\x1a\n" +
	"\bstreamId\x18\x01 \x01(\tR\bstreamId\"\b\n" +
	"\x06Cancel\"\x06\n" +
	"\x04Done\"\xf8\x01\n" +
	"\n" +
	"StreamFlow\x12\x1c\n" +
	"\bstreamId\x18\x01 \x01(\tH\x00R\bstreamId\x121\n" +
	"\aheaders\x18\x02 \x01(\v2\x15.tunnel.TunnelHeadersH\x00R\aheaders\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\f.tunnel.DataH\x00R\x04data\x12(\n" +
	"\x06cancel\x18\x04 \x01(\v2\x0e.tunnel.CancelH\x00R\x06cancel\x12\"\n" +
	"\x04done\x18\x05 \x01(\v2\f.tunnel.DoneH\x00R\x04done\x12\x1e\n" +
	"\tkeepalive\x18\x06 \x01(\tH\x00R\tkeepaliveB\a\n" +
	"\x05event\"\x14\n" +
	"\x12StreamFlowResponse\"\x1d\n" +
	"\vPingRequest\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x04R\x02ts\":\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x04R\x02ts\x12\x1a\n" +
	"\bechoedTs\x18\x04 \x01(\x04R\bechoedTs2\xd3\x02\n" +
	"\rTunnelService\x126\n" +
	"\x05Hello\x12\x14.tunnel.HelloRequest\x1a\x15.tunnel.HelloResponse\"\x00\x123\n" +
	"\x04Ping\x12\x13.tunnel.PingRequest\x1a\x14.tunnel.PingResponse\"\x00\x12G\n" +
	"\x0eWaitForRequest\x12\x1a.tunnel.WaitForRequestArgs\x1a\x15.tunnel.TunnelRequest\"\x000\x01\x12O\n" +
	"\x19DataFlowAgentToController\x12\x12.tunnel.StreamFlow\x1a\x1a.tunnel.StreamFlowResponse\"\x00(\x01\x12;\n" +
	"\n" +
	"RunRequest\x12\x15.tunnel.TunnelRequest\x1a\x12.tunnel.StreamFlow\"\x000\x01B\vZ\t./;tunnelb\x06proto3"

var (
	file_internal_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_internal_tunnel_tunnel_proto_rawDescData []byte
)

func file_internal_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_internal_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_internal_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tunnel_tunnel_proto_rawDesc), len(file_internal_tunnel_tunnel_proto_rawDesc)))
	})
	return file_internal_tunnel_tunnel_proto_rawDescData
}

var file_internal_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_tunnel_tunnel_proto_goTypes = []any{
	(*Annotation)(nil),          // 0: tunnel.Annotation
	(*EndpointHealth)(nil),      // 1: tunnel.EndpointHealth
	(*HelloRequest)(nil),        // 2: tunnel.HelloRequest
	(*AgentInfo)(nil),           // 3: tunnel.AgentInfo
	(*HelloResponse)(nil),       // 4: tunnel.HelloResponse
	(*Data)(nil),                // 5: tunnel.Data
	(*TunnelHeaders)(nil),       // 6: tunnel.TunnelHeaders
	(*HttpHeader)(nil),          // 7: tunnel.HttpHeader
	(*WaitForRequestArgs)(nil),  // 8: tunnel.WaitForRequestArgs
	(*TunnelRequest)(nil),       // 9: tunnel.TunnelRequest
	(*StartTunnelResponse)(nil), // 10: tunnel.StartTunnelResponse
	(*Cancel)(nil),              // 11: tunnel.Cancel
	(*Done)(nil),                // 12: tunnel.Done
	(*StreamFlow)(nil),          // 13: tunnel.StreamFlow
	(*StreamFlowResponse)(nil),  // 14: tunnel.StreamFlowResponse
	(*PingRequest)(nil),         // 15: tunnel.PingRequest
	(*PingResponse)(nil),        // 16: tunnel.PingResponse
}
var file_internal_tunnel_tunnel_proto_depIdxs = []int32{
	0,  // 0: tunnel.EndpointHealth.annotations:type_name -> tunnel.Annotation
	1,  // 1: tunnel.HelloRequest.endpoints:type_name -> tunnel.EndpointHealth
	3,  // 2: tunnel.HelloRequest.agentInfo:type_name -> tunnel.AgentInfo
	0,  // 3: tunnel.AgentInfo.annotations:type_name -> tunnel.Annotation
	1,  // 4: tunnel.HelloResponse.endpoints:type_name -> tunnel.EndpointHealth
	0,  // 5: tunnel.HelloResponse.annotations:type_name -> tunnel.Annotation
	7,  // 6: tunnel.TunnelHeaders.headers:type_name -> tunnel.HttpHeader
	7,  // 7: tunnel.TunnelRequest.headers:type_name -> tunnel.HttpHeader
	6,  // 8: tunnel.StreamFlow.headers:type_name -> tunnel.TunnelHeaders
	5,  // 9: tunnel.StreamFlow.data:type_name -> tunnel.Data
	11, // 10: tunnel.StreamFlow.cancel:type_name -> tunnel.Cancel
	12, // 11: tunnel.StreamFlow.done:type_name -> tunnel.Done
	2,  // 12: tunnel.TunnelService.Hello:input_type -> tunnel.HelloRequest
	15, // 13: tunnel.TunnelService.Ping:input_type -> tunnel.PingRequest
	8,  // 14: tunnel.TunnelService.WaitForRequest:input_type -> tunnel.WaitForRequestArgs
	13, // 15: tunnel.TunnelService.DataFlowAgentToController:input_type -> tunnel.StreamFlow
	9,  // 16: tunnel.TunnelService.RunRequest:input_type -> tunnel.TunnelRequest
	4,  // 17: tunnel.TunnelService.Hello:output_type -> tunnel.HelloResponse
	16, // 18: tunnel.TunnelService.Ping:output_type -> tunnel.PingResponse
	9,  // 19: tunnel.TunnelService.WaitForRequest:output_type -> tunnel.TunnelRequest
	14, // 20: tunnel.TunnelService.DataFlowAgentToController:output_type -> tunnel.StreamFlowResponse
	13, // 21: tunnel.TunnelService.RunRequest:output_type -> tunnel.StreamFlow
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_tunnel_tunnel_proto_init() }
func file_internal_tunnel_tunnel_proto_init() {
	if File_internal_tunnel_tunnel_proto != nil {
		return
	}
	file_internal_tunnel_tunnel_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamFlow_StreamId)(nil),
		(*StreamFlow_Headers)(nil),
		(*StreamFlow_Data)(nil),
		(*StreamFlow_Cancel)(nil),
		(*StreamFlow_Done)(nil),
		(*StreamFlow_Keepalive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tunnel_tunnel_proto_rawDesc), len(file_internal_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_internal_tunnel_tunnel_proto_depIdxs,
		MessageInfos:      file_internal_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_internal_tunnel_tunnel_proto = out.File
	file_internal_tunnel_tunnel_proto_goTypes = nil
	file_internal_tunnel_tunnel_proto_depIdxs = nil
}
