//
// Copyright 2021-2023 OpsMx, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: internal/tunnel/tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelService_Hello_FullMethodName                     = "/tunnel.TunnelService/Hello"
	TunnelService_Ping_FullMethodName                      = "/tunnel.TunnelService/Ping"
	TunnelService_WaitForRequest_FullMethodName            = "/tunnel.TunnelService/WaitForRequest"
	TunnelService_DataFlowAgentToController_FullMethodName = "/tunnel.TunnelService/DataFlowAgentToController"
	TunnelService_RunRequest_FullMethodName                = "/tunnel.TunnelService/RunRequest"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service (runs on the controller)
type TunnelServiceClient interface {
	// Initial handshake, sent from agent to controller on the control connection, before any other messages.
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Keep alive, sent from the agent to the controller, on control and data connections.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// The agent will perform a long-running call to WaitForRequest() and handle
	// any HTTP request found.
	WaitForRequest(ctx context.Context, in *WaitForRequestArgs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TunnelRequest], error)
	// DataFlowAgentToController is the conduit for an agent to send and manage the
	// flow of data for a specific HTTP response.
	DataFlowAgentToController(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamFlow, StreamFlowResponse], error)
	// The agent will call RunRequest() when it wants the controller to perform
	// an HTTP fetch.
	RunRequest(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFlow], error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, TunnelService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, TunnelService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) WaitForRequest(ctx context.Context, in *WaitForRequestArgs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TunnelRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], TunnelService_WaitForRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaitForRequestArgs, TunnelRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_WaitForRequestClient = grpc.ServerStreamingClient[TunnelRequest]

func (c *tunnelServiceClient) DataFlowAgentToController(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamFlow, StreamFlowResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[1], TunnelService_DataFlowAgentToController_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlow, StreamFlowResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_DataFlowAgentToControllerClient = grpc.ClientStreamingClient[StreamFlow, StreamFlowResponse]

func (c *tunnelServiceClient) RunRequest(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFlow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[2], TunnelService_RunRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelRequest, StreamFlow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_RunRequestClient = grpc.ServerStreamingClient[StreamFlow]

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility.
//
// Service (runs on the controller)
type TunnelServiceServer interface {
	// Initial handshake, sent from agent to controller on the control connection, before any other messages.
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// Keep alive, sent from the agent to the controller, on control and data connections.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// The agent will perform a long-running call to WaitForRequest() and handle
	// any HTTP request found.
	WaitForRequest(*WaitForRequestArgs, grpc.ServerStreamingServer[TunnelRequest]) error
	// DataFlowAgentToController is the conduit for an agent to send and manage the
	// flow of data for a specific HTTP response.
	DataFlowAgentToController(grpc.ClientStreamingServer[StreamFlow, StreamFlowResponse]) error
	// The agent will call RunRequest() when it wants the controller to perform
	// an HTTP fetch.
	RunRequest(*TunnelRequest, grpc.ServerStreamingServer[StreamFlow]) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServiceServer struct{}

func (UnimplementedTunnelServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTunnelServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTunnelServiceServer) WaitForRequest(*WaitForRequestArgs, grpc.ServerStreamingServer[TunnelRequest]) error {
	return status.Error(codes.Unimplemented, "method WaitForRequest not implemented")
}
func (UnimplementedTunnelServiceServer) DataFlowAgentToController(grpc.ClientStreamingServer[StreamFlow, StreamFlowResponse]) error {
	return status.Error(codes.Unimplemented, "method DataFlowAgentToController not implemented")
}
func (UnimplementedTunnelServiceServer) RunRequest(*TunnelRequest, grpc.ServerStreamingServer[StreamFlow]) error {
	return status.Error(codes.Unimplemented, "method RunRequest not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}
func (UnimplementedTunnelServiceServer) testEmbeddedByValue()                       {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_WaitForRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WaitForRequestArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TunnelServiceServer).WaitForRequest(m, &grpc.GenericServerStream[WaitForRequestArgs, TunnelRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_WaitForRequestServer = grpc.ServerStreamingServer[TunnelRequest]

func _TunnelService_DataFlowAgentToController_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).DataFlowAgentToController(&grpc.GenericServerStream[StreamFlow, StreamFlowResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_DataFlowAgentToControllerServer = grpc.ClientStreamingServer[StreamFlow, StreamFlowResponse]

func _TunnelService_RunRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TunnelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TunnelServiceServer).RunRequest(m, &grpc.GenericServerStream[TunnelRequest, StreamFlow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_RunRequestServer = grpc.ServerStreamingServer[StreamFlow]

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _TunnelService_Hello_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TunnelService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WaitForRequest",
			Handler:       _TunnelService_WaitForRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DataFlowAgentToController",
			Handler:       _TunnelService_DataFlowAgentToController_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RunRequest",
			Handler:       _TunnelService_RunRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/tunnel/tunnel.proto",
}
