#
# Copyright 2026 OpsMx, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM alpine:3

RUN apk update && apk upgrade --no-cache && apk add --no-cache ca-certificates curl
RUN update-ca-certificates ; exit 0
RUN mkdir /local /local/ca-certificates && rm -rf /usr/local/share/ca-certificates && ln -s /local/ca-certificates /usr/local/share/ca-certificates

WORKDIR /app
COPY docker/run.sh /app/run.sh
COPY dist/agent-client /app/agent-client

EXPOSE 9102

ENTRYPOINT ["/bin/sh", "/app/run.sh"]
CMD ["/app/agent-client"]
